#pragma once

#include <string>
#include <glad/glad.h>
#include <glm/glm.hpp>

struct TextRenderer
{
    GLuint vao = 0;             // OpenGL vertex array object used for 2D text geometry in screen-space rasterization
    GLuint vbo = 0;             // OpenGL vertex buffer object storing text vertices generated by stb_easy_font
    GLuint program = 0;         // GLSL program used for forward rasterization of untextured text quads
    GLint  uColorLoc = -1;      // Location of uniform controlling RGBA color of rendered text
    GLint  uScreenSizeLoc = -1; // Location of uniform storing current viewport size for pixel-to-NDC conversion
};

// screenWidth kept for API compatibility with potential future resolution-dependent setups; current implementation queries viewport directly
bool initTextRenderer(TextRenderer& tr, unsigned int screenWidth);

void shutdownTextRenderer(TextRenderer& tr);

// Renders one line of ASCII text as 2D geometry in screen space using OpenGL forward rasterization and stb_easy_font-generated vertices
// x,y treated as pixel coordinates with text horizontally centered on x and baseline at y
// scale controls uniform font scaling in pixel space (1.0 = base size)
// shadowAlpha controls opacity of black shadow behind text (0.0 = no shadow, 1.0 = fully opaque shadow)
void drawTextLine(const TextRenderer& tr,
                  unsigned int screenWidth,
                  int x, int y,
                  float scale,
                  float shadowAlpha,
                  const std::string& text,
                  const glm::vec4& color);
